language: node_js
node_js:
    - "stable"
before_script:
    - npm install -g grunt-cli
deploy:
	provider: npm
	api_key: "ea07ce5b-9110-41cb-bb9a-2527435ac3b8"
	email: "oleksii.moroz@tum.de"
	on:
    	all_branches: true
    skip_cleanup: true

