language: node_js
node_js:
- stable
before_script:
- npm install -g grunt-cli && npm run-script build
deploy:
  provider: npm
  email: oleksii.moroz@hotmail.com
  api_key:
    secure: ZeGE7jlrimXfFBsZYl3Vd5q4o++MYrwJmYG9VmesmUVd1t/xsVvy4011MA2WHGdUMFW5Y8UISH3c31lL597KtQCELJyv5SCOKwix564cfOJdoB+CsI0QGK9WjuJ4J/o9EU7uC2wHmShQOqs4RGNi+CEtBUVCSDCECVaJJLxY10IinK3gm3nJioBXJb6XRt27xcguER9NRSOLb9hA77au6zpPE96k63nNmp5UmVneEi/kIG4H3OusXMm5K7Hj+zzhj/5lzXMsDqVLYaVhUJVXfWQnPx1sXKqaqApNZYbuIn3HRcoz5wN8RukoGD55HBRgVMNKmYzEFS5rjsoqR5hcYPFcGCCIEX3BQ8pNCW3JQ18+3k6ChIexat2FC4ncMXu6/V5v4JDo2Mwfp/cg3S7d8yHnN46ngO+Mi2HmLVkxEmvdpdz6v0hm5dVh3SzsjnOTLZoIgBZbObOP+bQLtkh014J4LCqCiyDP63XUD0i+mc53Yl7DdBL8af3XJdKKpJBs1Pq8SaWuICrqFlXiD8FVit0qpjlFeYCzACjeXKcmn8GrsNmg6LqmaWbpiOJXhlxnckH2qGb+zChHLC3Dt1frVnaqqW+Bl2rWlFzWU8MAqw27GhzwiTLrj7F9j20icfqc0vCfiUachiMkNdQuqXmHM58u+ZLUVC//e+EogMwAFrQ=
  on:
    repo: Rostlab/JS16_ProjectC_Group10
    branch: develop
