language: node_js
node_js:
- stable
before_script:
- npm install -g grunt-cli
- bash scripts/deploy.sh
deploy:
  provider: npm
  email: oleksii.moroz@hotmail.com
  api_key:
    secure: ZeGE7jlrimXfFBsZYl3Vd5q4o++MYrwJmYG9VmesmUVd1t/xsVvy4011MA2WHGdUMFW5Y8UISH3c31lL597KtQCELJyv5SCOKwix564cfOJdoB+CsI0QGK9WjuJ4J/o9EU7uC2wHmShQOqs4RGNi+CEtBUVCSDCECVaJJLxY10IinK3gm3nJioBXJb6XRt27xcguER9NRSOLb9hA77au6zpPE96k63nNmp5UmVneEi/kIG4H3OusXMm5K7Hj+zzhj/5lzXMsDqVLYaVhUJVXfWQnPx1sXKqaqApNZYbuIn3HRcoz5wN8RukoGD55HBRgVMNKmYzEFS5rjsoqR5hcYPFcGCCIEX3BQ8pNCW3JQ18+3k6ChIexat2FC4ncMXu6/V5v4JDo2Mwfp/cg3S7d8yHnN46ngO+Mi2HmLVkxEmvdpdz6v0hm5dVh3SzsjnOTLZoIgBZbObOP+bQLtkh014J4LCqCiyDP63XUD0i+mc53Yl7DdBL8af3XJdKKpJBs1Pq8SaWuICrqFlXiD8FVit0qpjlFeYCzACjeXKcmn8GrsNmg6LqmaWbpiOJXhlxnckH2qGb+zChHLC3Dt1frVnaqqW+Bl2rWlFzWU8MAqw27GhzwiTLrj7F9j20icfqc0vCfiUachiMkNdQuqXmHM58u+ZLUVC//e+EogMwAFrQ=
  on:
    repo: Rostlab/JS16_ProjectC_Group10
    branch: develop
env:
  global:
    secure: TdDsJlsrn9lALeHPxVsdsuzC40htGAxXJOvgFB+9hQsPHOg1b1CyVOKWCiVIMt+lvLADpsXx2KLbpUeYZ7eWas1km25nXOpndzbBu5TZZUOxSFUWKMMvFEic20NVsKZfcb4KyFZ2GtU7SWmK3RyfKJFflwYbD5TWZbYVF9JXaOQRMGDVjXufPnpAALosf9tIbK8HIz0gXvgc8qEIHA1vWCVwx6vhIVsn6uAN4tukUxees72xpWR262VyjyS9uK3OMDJHXxzaSS488EfOGOGgFyrgVrRG4EXaAWIe7QwKEjORf95kExR/7C1Bv+6oEkiwrc/DLqfY0oA3pjCSwX2mSw6tT9smPSpQ4QRzfUDqXNdIy7BM10L/uW1iS533e5KNDBNPG9fyxq0gnHXumJuzK0HP017ICjOFywmy7TU+W9PwP4wGVXcc17IyltR6knunNT5e1AO296X6ZMjPqDuq0X/62LCpLEFzHb1HpjlFtkZ/kF4L3tcfNLOrIzKAHxxbpeIQ6+dIBp87k2Xu11q6REw9NjThBSrM6h3K9R3XyrlzklA5TXu0x21DpoA0+UtqkFRloLr+0XbmUsvDQKqXOrJd6VidAjh5RSvcfdfjvXxCRezMqklDv6rg99IhPXEL0LVb+nkl/pycpNGIhty4qkHSQ1K5Yk+fpnIwNDlVu54=
